### ISSUE TITLE
Create user without department fails because DepartmentId is set to zero

### ISSUE THREAD

**Issue by gpdoud** [gpdoud/ams2-client-solution#28]
This issue probably requires a change on both the front end

In the user-create.component, the user property is initialized to an empty instance of a User. The DepartmentId is set to zero but should be set to NULL indicating the user is NOT associated with a department. By being set to zero, the create fails in the back end controller because zero is not a valid department.Id.

**Comment by fieldsmu** [comment]
This issue was solved by changing the property values in the user constructor. Specifically, the DepartmentId _was_ set to zero and is _now_ set to null.
