### ISSUE TITLE
Sort lists by column

### ISSUE THREAD

**Issue by gpdoud** [gpdoud/ams2-client-solution#3]
As the number of records in each asset gets larger, to allow users to find the asset they're looking for, it required being able to sort the list by a number of columns in the asset.

Sorting will be done by clicking the column heading in the list and the data will be sorted in ascending sequence. It would be good to allow the user, after sorting a column in ascending sequence, to click the column again and have the sort be in descending sequence. 

Some indicator as to which column is being sorted and what order the sort is in would be good but not required.

**Comment by michaelbuchanan23** [comment]
case insensitive sorting was added on 7/30/2018
